# Generated by Django 4.1.7 on 2024-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_connectuser_recovery_pin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectuser",
            name="recovery_pin",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
