# Generated by Django 4.1.7 on 2024-07-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_credential_usercredential"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectuser",
            name="deactivation_token",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="connectuser",
            name="deactivation_token_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
