# Generated by Django 4.1.7 on 2024-08-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_connectuser_deactivation_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connectuser",
            options={},
        ),
        migrations.AddConstraint(
            model_name="connectuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("phone_number",),
                name="phone_number_active_user",
            ),
        ),
    ]
