# Generated by Django 4.1.7 on 2024-10-10 10:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_connectuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectuser",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
