# Generated by Django 4.1.7 on 2024-06-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_connectuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonedevice",
            name="otp_last_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
