# Generated by Django 4.1.7 on 2025-01-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_phonedevice_otp_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonedevice",
            name="attempts",
            field=models.IntegerField(default=1),
        ),
    ]
