# Generated by Django 4.1.7 on 2025-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_phonedevice_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectuser",
            name="photo",
            field=models.TextField(blank=True, help_text="Base64 encoded image", null=True),
        ),
    ]
