# Generated by Django 4.1.7 on 2025-05-23 12:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_phonedevice_attempts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationSession",
            fields=[
                ("key", models.CharField(max_length=70, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires", models.DateTimeField()),
                ("phone_number", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("is_phone_validated", models.BooleanField(default=False)),
            ],
        ),
    ]
