# Generated by Django 4.1.7 on 2025-05-22 15:29

from django.db import migrations, models
from users.models import ConnectUser


def set_existing_users(apps, schema):
    ConnectUserModel = apps.get_model("users.ConnectUser")
    ConnectUserModel.objects.all().update(
        device_security=ConnectUser.DeviceSecurity.PIN,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_configurationsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectuser",
            name="device_security",
            field=models.CharField(
                choices=[("pin", "pin"), ("biometric", "biometric")], default="biometric", max_length=15
            ),
        ),
        migrations.RunPython(set_existing_users, migrations.RunPython.noop),
    ]
