# Generated by Django 4.1.7 on 2025-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_connectuser_device_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsession",
            name="failed_backup_code_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
