# Generated by Django 4.1.7 on 2025-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_configurationsession_incorrect_backup_code_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsession",
            name="gps_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
