# Generated by Django 4.1.7 on 2025-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_configurationsession_gps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsession',
            name='invited_user',
            field=models.BooleanField(default=False),
        ),
    ]
