# Generated by Django 4.1.7 on 2025-06-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_configurationsession_invited_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectuser",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
