# Generated by Django 4.1.7 on 2025-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_connectuser_is_locked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurationsession",
            name="failed_backup_code_attempts",
        ),
        migrations.AddField(
            model_name="connectuser",
            name="failed_backup_code_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
