# Generated by Django 4.1.7 on 2025-07-02 13:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_configurationsession_failed_backup_code_attempts_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credential",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="organization_slug",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="slug",
        ),
        migrations.AddField(
            model_name="credential",
            name="app_or_opp_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credential",
            name="issuing_authority",
            field=models.CharField(choices=[("CONNECT", "CONNECT"), ("HQ, HQ")], default="CONNECT", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credential",
            name="level",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="type",
            field=models.CharField(
                choices=[("APP_ACTIVITY", "APP_ACTIVITY"), ("LEARN", "LEARN"), ("DELIVER", "DELIVER")],
                default="DELIVER",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="credential",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
