# Generated by Django 4.1.7 on 2025-07-04 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def delete_existing_credentials(apps, schema_editor):
    """
    Delete all existing credential records before schema changes.
    This is being done so that defaults for required fields to not
    have to be set, avoiding misleading data.
    """
    Credential = apps.get_model("users", "Credential")
    Credential.objects.all().delete()

def reverse_delete_credentials(apps, schema_editor):
    """
    The deleting of existing records operation cannot be reversed,
    however this function is here to prevent an error from raising
    when attempting to reverse this migration.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_sessionphonedevice_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_existing_credentials, reverse_delete_credentials),
        migrations.RenameField(
            model_name="credential",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="organization_slug",
        ),
        migrations.RemoveField(
            model_name="credential",
            name="slug",
        ),
        migrations.AddField(
            model_name="credential",
            name="app_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="issuing_authority",
            field=models.CharField(choices=[("CONNECT", "CONNECT"), ("HQ", "HQ")], max_length=50),
        ),
        migrations.AddField(
            model_name="credential",
            name="level",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="credential",
            name="opportunity_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="type",
            field=models.CharField(
                choices=[("APP_ACTIVITY", "APP_ACTIVITY"), ("LEARN", "LEARN"), ("DELIVER", "DELIVER")],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="sessionphonedevice",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
