# Generated by Django 4.1.7 on 2025-07-17 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_sessionphonedevice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceIntegritySample",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device_id", models.CharField(max_length=255)),
                ("google_verdict", models.JSONField()),
                ("processed_response", models.CharField(blank=True, max_length=100)),
                (
                    "processed_verdict",
                    models.CharField(
                        blank=True,
                        choices=[("passed", "passed"), ("failed", "failed")],
                        default="passed",
                        max_length=50,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_demo_user", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
