# Generated by Django 4.1.7 on 2025-07-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_add_deviceintegritysample"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionphonedevice",
            name="has_manual_otp",
            field=models.BooleanField(default=False),
        ),
    ]
