# Generated by Django 4.1.7 on 2025-07-25 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_credential_table_cleanup_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credential",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="credential",
            name="app_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="level",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="credential",
            name="opportunity_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="credential",
            name="type",
            field=models.CharField(
                choices=[("APP_ACTIVITY", "APP_ACTIVITY"), ("LEARN", "LEARN"), ("DELIVER", "DELIVER")],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="credential",
            name="slug",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sessionphonedevice",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.issuingauthority"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="credential",
            unique_together={("issuer", "level", "type", "slug")},
        ),
        migrations.RemoveField(
            model_name="credential",
            name="organization_slug",
        ),
    ]
