# Generated by Django 4.1.7 on 2025-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_sessionphonedevice_has_manual_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsession",
            name="device_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
