# Generated by Django 4.1.7 on 2025-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_configurationsession_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsession",
            name="otp_sms_strategy",
            field=models.CharField(
                choices=[("firebase", "firebase"), ("personal_id", "personal_id")], default="firebase", max_length=15
            ),
        ),
    ]
