# Generated by Django 4.1.7 on 2025-09-19 12:54

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_configurationsession_device_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="connectuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"), name="unique_lower_user"
            ),
        ),
    ]
