# Generated by Django 4.1.7 on 2025-10-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_connectuser_unique_lower_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serverkeys",
            options={"verbose_name": "Server Keys", "verbose_name_plural": "Server Keys"},
        ),
    ]
