# Generated by Django 4.1.7 on 2025-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_serverkeys_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectuser",
            name="last_session_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
