# Generated by Django 4.1.7 on 2025-11-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_serverkeys_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectuser",
            name="hq_sso_date",
            field=models.DateTimeField(null=True),
        ),
    ]
