# Generated by Django 4.1.7 on 2025-11-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_serverkeys_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnalyticsData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("has_viewed_work_history", models.DateTimeField(null=True)),
                ("has_sent_message", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
