# Generated by Django 4.1.7 on 2026-03-11 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_connectuser_hq_sso_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationsession",
            name="device",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="UserDeviceInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("device", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=128)),
                ("last_accessed", models.DateTimeField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_accessed"],
            },
        ),
    ]
