# Generated by Django 4.1.7 on 2026-06-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_configurationsession_device_userdeviceinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionEmailOTPDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The human-readable name of this device.", max_length=64)),
                ("confirmed", models.BooleanField(default=True, help_text="Is this device ready for use?")),
                ("token", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp of the moment of expiry of the saved token.",
                    ),
                ),
                ("otp_last_sent", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=1)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="UserEmailOTPDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The human-readable name of this device.", max_length=64)),
                ("confirmed", models.BooleanField(default=True, help_text="Is this device ready for use?")),
                ("token", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp of the moment of expiry of the saved token.",
                    ),
                ),
                ("otp_last_sent", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=1)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name="configurationsession",
            name="verified_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name="connectuser",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), models.Q(("email", ""), _negated=True)),
                fields=("email",),
                name="email_active_user",
            ),
        ),
        migrations.AddField(
            model_name="useremailotpdevice",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="sessionemailotpdevice",
            name="session",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.configurationsession"),
        ),
        migrations.AddField(
            model_name="sessionemailotpdevice",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="useremailotpdevice",
            constraint=models.UniqueConstraint(fields=("user", "email"), name="user_email_otp_device_user_email"),
        ),
        migrations.AddConstraint(
            model_name="sessionemailotpdevice",
            constraint=models.UniqueConstraint(
                fields=("session", "email"), name="session_email_otp_device_session_email"
            ),
        ),
    ]
