# Generated by Django 4.1.7 on 2026-06-24 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_sessionemailotpdevice_useremailotpdevice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercredential",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
    ]
