# Generated by Django 5.2.17 on 2026-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_usercredential_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedevice',
            name='failed_verifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionemailotpdevice',
            name='failed_verifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionphonedevice',
            name='failed_verifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useremailotpdevice',
            name='failed_verifications',
            field=models.IntegerField(default=0),
        ),
    ]
