# Generated by Django 5.2.17 on 2026-09-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_otpdevice_failed_verifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedevice',
            name='burned_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionemailotpdevice',
            name='burned_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionphonedevice',
            name='burned_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useremailotpdevice',
            name='burned_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
