# Generated by Django 5.2.17 on 2026-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_otpdevice_failed_verifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationsession',
            name='backup_code_verified',
            field=models.BooleanField(default=False),
        ),
    ]
