class ErrorCodes:
    MISSING_DATA = "MISSING_DATA"
    INTEGRITY_ERROR = "INTEGRITY_ERROR"
    INTEGRITY_SERVICE_UNAVAILABLE = "INTEGRITY_SERVICE_UNAVAILABLE"


INTEGRITY_TOKEN_HEADER_KEY = "CC-Integrity-Token"
INTEGRITY_REQUEST_HASH_KEY = "CC-Request-Hash"
