class ErrorCodes:
    INTEGRITY_DATA_MISSING = "INTEGRITY_DATA_MISSING"
    INTEGRITY_ERROR = "INTEGRITY_ERROR"


INTEGRITY_TOKEN_HEADER_KEY = "CC-Integrity-Token"
INTEGRITY_REQUEST_HASH_KEY = "CC-Request-Hash"
