# Generated by Django 4.1.7 on 2024-11-06 01:13

from django.db import migrations, models
import oauth2_provider.generators


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messageserver",
            name="oauth_application",
        ),
        migrations.AddField(
            model_name="messageserver",
            name="secret_key",
            field=models.CharField(
                default=oauth2_provider.generators.generate_client_secret,
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="messageserver",
            name="server_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=100,
                unique=True,
            ),
        ),
    ]
