# Generated by Django 4.1.7 on 2024-12-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_remove_messageserver_oauth_application_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="direction",
            field=models.CharField(choices=[("M", "Mobile"), ("S", "Server")], default="M", max_length=4),
        ),
    ]
