# Generated by Django 4.1.7 on 2025-03-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_message_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="user_consent",
            field=models.BooleanField(default=True),
        ),
    ]
