# Generated by Django 4.1.7 on 2025-03-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0004_alter_channel_user_consent_alter_message_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="channel_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="direction",
            field=models.CharField(
                choices=[("M", "Mobile"), ("S", "Server")], max_length=4
            ),
        ),
    ]
