# Generated by Django 4.1.7 on 2025-07-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_serverkeys_rename_name_credential_title_and_more"),
        ("messaging", "0005_channel_channel_name_alter_message_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="messageserver",
            name="server_credentials",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="users.serverkeys"),
        ),
    ]
