# Generated by Django 4.1.7 on 2025-08-29 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messaging", "0006_messageserver_server_credentials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("CONNECT", "Connect"), ("MESSAGING", "Messaging")], default="CONNECT", max_length=50
                    ),
                ),
                ("json", models.JSONField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("received", models.DateTimeField(blank=True, null=True)),
                (
                    "message_id",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="messaging.message"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
