# Generated by Django 5.2.17 on 2026-10-05 14:38

import django.db.models.deletion
import messaging.models
import utils.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0007_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        storage=utils.storage.get_message_attachment_storage,
                        upload_to=messaging.models.attachment_storage_key,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="format",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="rich_text",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="version",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                condition=models.Q(("expires_at__isnull", False)), fields=["expires_at"], name="message_expires_at"
            ),
        ),
        migrations.AddField(
            model_name="messageattachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="messaging.message"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageattachment",
            constraint=models.UniqueConstraint(fields=("message", "name"), name="unique_attachment_name_per_message"),
        ),
        migrations.AddConstraint(
            model_name="messageattachment",
            constraint=models.UniqueConstraint(
                fields=("message", "position"), name="unique_attachment_position_per_message"
            ),
        ),
    ]
