TEST_NUMBER_PREFIX = "+7426"

NO_RECOVERY_PHONE_ERROR = "Recovery phone number does not exist for user"


MAX_PHOTO_SIZE = 1 * 1024 * 1024  # 1 MB


class ErrorCodes:
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_SECRET_KEY = "INVALID_SECRET_KEY"
    USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    NO_RECOVERY_PIN_SET = "NO_RECOVERY_PIN_SET"
    INCORRECT_CODE = "INCORRECT_CODE"
    INVALID_STEP = "INVALID_STEP"
    MISSING_RECOVERY_PIN = "MISSING_RECOVERY_PIN"
    FAILED_TO_UPLOAD = "FAILED_TO_UPLOAD"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    MISSING_DATA = "MISSING_DATA"
    PHONE_MISMATCH = "PHONE_MISMATCH"
    MISSING_TOKEN = "MISSING_TOKEN"
    FAILED_VALIDATING_TOKEN = "FAILED_VALIDATING_TOKEN"
    NAME_REQUIRED = "NAME_REQUIRED"
